"""Canned FTS5 queries for the caching questions people actually ask
about Cargo/rustc (issue #1). Single source of truth, consumed by:
  - build_site.py (UI example-search chips + _meta.json)
  - tests/test_queries.py (relevance regression tests per release DB)
  - queries.md (hand-mirrored for human browsing)

`targets` is a list of path substrings; a query passes if at least one
top-N hit's `documents.path` contains one of them.
"""

QUERIES = [
    {"question": "What inputs go into a unit fingerprint?",
     "match": "fingerprint AND (input OR hash OR dirty OR fresh)",
     "targets": ["fingerprint/mod.rs", "build-cache.md"]},
    {"question": "Where does Cargo persist freshness state on disk (.fingerprint/)?",
     "match": '"fingerprint" AND (directory OR json OR "on disk" OR store)',
     "targets": ["fingerprint/mod.rs", "build-cache.md"]},
    {"question": "What lives in target/, deps/, incremental/; rlib/rmeta linking layout?",
     "match": "target AND (deps OR incremental OR rlib OR rmeta)",
     "targets": ["build-cache.md", "compilation_files.rs"]},
    {"question": "How does Cargo track discovered source inputs via dep-info .d files?",
     "match": '"dep info" OR ("d files") OR (discovered AND dependency)',
     "targets": ["dep_info.rs", "build-cache.md"]},
    {"question": "How are --extern dependencies identified (path/contents/crate hash)?",
     "match": "extern AND (rmeta OR rlib OR metadata OR hash)",
     "targets": ["compilation_files.rs", "locator.rs", "creader.rs"]},
    {"question": "When does a build script re-run (rerun-if-changed / -env-changed)?",
     "match": '("rerun if changed") OR ("rerun if env changed") OR ("build script" AND rerun)',
     "targets": ["build-scripts.md", "custom_build.rs"]},
    {"question": "What invalidates the cache besides source -- rustflags/profile/features/LTO/codegen-units?",
     "match": '(rustflags OR profile OR feature OR lto OR "codegen units") AND (hash OR fingerprint OR metadata)',
     "targets": ["fingerprint/mod.rs", "compile_kind.rs"]},
    {"question": "How to make artifacts path-independent for cross-workspace cache sharing?",
     "match": '("remap path prefix") OR (remap AND path AND (prefix OR portable))',
     "targets": ["command-line-arguments.md", "dep_info.rs"]},
    {"question": "Metadata pipelining -- when can a downstream crate start before .rlib is done?",
     "match": '(pipelin OR metadata) AND (rmeta OR ready OR "job queue")',
     "targets": ["job_queue/mod.rs", "libs-and-metadata.md"]},
    {"question": "When is .rmeta enough vs .rlib required?",
     "match": "rmeta AND rlib AND (link OR downstream OR codegen)",
     "targets": ["libs-and-metadata.md", "compilation_files.rs"]},
    {"question": "Can incremental state be relocated between machines/dirs?",
     "match": 'incremental AND (relocat OR portab OR "work product" OR "dependency graph")',
     "targets": ["incremental-compilation.md", "codegen-options/index.md"]},
    {"question": "Which crate types invoke the linker / what is unsafe to cache?",
     "match": '("proc-macro" OR dylib OR cdylib OR bin) AND (link OR cache OR "not cacheable")',
     "targets": ["Rust.md", "rust.rs", "back/link.rs"]},
    {"question": "What's inside rustc's incremental on-disk cache (dep-graph, query results, work products)?",
     "match": 'incremental AND ("work product" OR "dep graph" OR "query cache" OR serialized)',
     "targets": ["incremental-compilation.md", "serialization.md"]},
    {"question": "How do -C metadata / -C extra-filename disambiguate symbols + output filenames?",
     "match": '("extra filename") OR ("C metadata") OR (disambiguator AND crate)',
     "targets": ["command-line-arguments.md", "codegen-options/index.md", "compilation_files.rs"]},
    {"question": ".rmeta format + how a crate's SVH/hash is validated on load?",
     "match": '(rmeta OR metadata) AND (header OR version OR svh OR "strict version" OR validate)',
     "targets": ["rmeta/mod.rs", "locator.rs", "libs-and-metadata.md"]},
    {"question": "How does rustc locate + load crates (-L search paths, --extern, rlib/rmeta/dylib)?",
     "match": '(locate OR load) AND crate AND (extern OR "search path" OR rlib OR rmeta OR dylib)',
     "targets": ["locator.rs", "creader.rs", "command-line-arguments.md"]},
    {"question": "mtime vs checksum freshness -- how does Cargo decide a file changed?",
     "match": "(mtime OR timestamp OR modified OR checksum) AND (fresh OR fingerprint OR rebuild)",
     "targets": ["fingerprint/mod.rs", "build-cache.md"]},
    {"question": "How are env vars tracked (env!, rerun-if-env-changed, RUSTFLAGS) in the key?",
     "match": '(env OR environment OR rustflags) AND (variable OR "rerun if env changed" OR track OR fingerprint)',
     "targets": ["fingerprint/mod.rs", "custom_build.rs", "build-scripts.md"]},
    {"question": "How are include! / include_bytes! / include_str! inputs tracked?",
     "match": '(include OR "include str" OR "include bytes") AND (dep OR track OR source OR rerun)',
     "targets": ["dep_info.rs", "build-cache.md"]},
    {"question": "How does a dependency's fingerprint propagate -- an upstream change dirtying dependents?",
     "match": "fingerprint AND (dependency OR upstream OR propagat OR transitive) AND (dirty OR invalidat OR recompil)",
     "targets": ["fingerprint/mod.rs", "unit_dependencies.rs"]},
    {"question": ".rlib archive internals -- object files, metadata object, symbol table?",
     "match": 'rlib AND (archive OR object OR "symbol table" OR member)',
     "targets": ["back/archive.rs", "back/metadata.rs", "libs-and-metadata.md"]},
    {"question": "Debug-info sidecars -- -C split-debuginfo, .dwo / .pdb / .dSYM?",
     "match": '("split debuginfo") OR (debuginfo AND (dwo OR pdb OR dsym OR split))',
     "targets": ["codegen-options/index.md", "back/link.rs"]},
    {"question": "How do codegen-units affect object outputs + determinism?",
     "match": '("codegen units") AND (object OR parallel OR determinis OR split)',
     "targets": ["codegen-options/index.md", "fingerprint/mod.rs"]},
    {"question": "Cross-compile: host vs target -- build-deps + proc-macros built for the host?",
     "match": '("build script" OR "proc macro" OR "build dependencies") AND host AND target',
     "targets": ["compile_kind.rs", "unit_dependencies.rs", "build-cache.md"]},
    {"question": "rustc's red-green algorithm -- when is a query result reused?",
     "match": 'query AND (red OR green OR reuse OR "try mark green" OR "dep node")',
     "targets": ["incremental-compilation.md"]},
    {"question": "What --emit output types exist (metadata / link / obj / dep-info / llvm-*)?",
     "match": 'emit AND (metadata OR link OR obj OR "dep info" OR llvm)',
     "targets": ["command-line-arguments.md"]},
    {"question": "Does panic strategy (abort/unwind) enter the cache key / affect ABI?",
     "match": "panic AND (abort OR unwind OR strategy) AND (fingerprint OR metadata OR abi)",
     "targets": ["fingerprint/mod.rs", "codegen-options/index.md",
                 "compilation_files.rs", "back/link.rs"]},
]
